### ISSUE TITLE
请问一下这个内存池模块是独立的吗，没看到它在分布式RPC以及muduo库的应用

### ISSUE THREAD

**Issue by liJay010** [Kohirus/Apollo#1]
请问一下这个内存池模块是独立的吗，没看到它在分布式RPC以及muduo库的应用

**Comment by Kohirus** [comment]
编译的时候可以选择加入内存池模块，内存池模块中对`new`和`delete`都做了重载，所以其他模块申请动态内存时都会使用内存池模块中的方法
